spring.application.name=java-pos-sql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/java-pos
spring.datasource.username=root
spring.datasource.password=
spring.database.driver-class-name=com.mysql.cj.jdbc.Driver